import * as fs from 'fs';
import { resolveSafePath } from './utils';

/**
 * Workspace-jailed drop-in for `fs`, given to code generated by `create_tool` (T14.22) instead
 * of the raw module. The built-in file tools (`read_file`/`write_file`/`delete_file`) already
 * route every path through `resolveSafePath` — a self-authored tool never did: the generated
 * module required the real, unrestricted `fs` directly (`custom_tools/*.js` is loaded via plain
 * `require()`/`import()` on every future startup — the VM sandbox in `createTool.ts` only ever
 * validates the code's *shape* once, at creation time, it is not a persistent execution jail).
 * A tool declaring itself harmless could reach anywhere the process could, e.g. `fs.rmSync` on a
 * path outside the workspace entirely. Wrapping each path-taking call closes that regardless of
 * what the tool claims about itself.
 *
 * Deliberately not a full `fs` proxy: only the sync methods a generated tool plausibly needs are
 * exposed. Anything else is simply not on this object — a generated tool referencing it fails
 * loudly (`fs.something is not a function`) rather than silently reaching the real module.
 */

function jail1<A extends any[], R>(fn: (path: string, ...rest: A) => R): (path: string, ...rest: A) => R {
  return (path, ...rest) => fn(resolveSafePath(path), ...rest);
}

function jail2<A extends any[], R>(fn: (a: string, b: string, ...rest: A) => R): (a: string, b: string, ...rest: A) => R {
  return (a, b, ...rest) => fn(resolveSafePath(a), resolveSafePath(b), ...rest);
}

export const jailedFs = {
  readFileSync: jail1(fs.readFileSync),
  writeFileSync: jail1(fs.writeFileSync),
  appendFileSync: jail1(fs.appendFileSync),
  existsSync: jail1(fs.existsSync),
  mkdirSync: jail1(fs.mkdirSync),
  readdirSync: jail1(fs.readdirSync),
  statSync: jail1(fs.statSync),
  lstatSync: jail1(fs.lstatSync),
  unlinkSync: jail1(fs.unlinkSync),
  rmSync: jail1(fs.rmSync),
  rmdirSync: jail1(fs.rmdirSync),
  copyFileSync: jail2(fs.copyFileSync),
  renameSync: jail2(fs.renameSync),
};
