/**
 * Shared types for multi-agent protocol and orchestration layer (T4.1).
 * Focuses on shared communication contracts: chat messages, tool calls,
 * turn outcomes, and team/plan configurations.
 */

export type ChatRole = 'system' | 'user' | 'assistant' | 'tool';

/** Tool call structure matching OpenAI-compatible Function Calling specifications. */
export interface ToolCall {
  id: string;
  type: 'function';
  function: { name: string; arguments: string };
}

/** Chat message structure used across Agent, ILLMProvider, and team/goal histories. */
export interface ChatMessage {
  role: ChatRole;
  content: string | null;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
  name?: string;
}

/** Outcome of an execution turn (team member, pipeline station, or goal step). */
export type TurnOutcome = 'completed' | 'interrupted' | 'continue' | 'failed';

/**
 * Origin of a protocol decision (T2.1):
 * structured tool call (report_status/route_next/cast_vote) -> textual regex fallback -> default.
 */
export type ProtocolSource = 'tool_call' | 'regex' | 'fallback';

/** Cast vote in a discussion round with voting enabled. */
export type Vote = 'APPROVO' | 'MODIFICARE' | 'RIFIUTO';

/** Objective acceptance criteria for iterative execution loops (T6.3). */
export interface AcceptanceCriteria {
  /** Shell command to execute (must return exit code 0 to pass acceptance). */
  command?: string;
  /** Relative or absolute path to a file that must exist on disk. */
  fileExists?: string;
  /** Relative or absolute path to a JSON file that must exist and parse cleanly. */
  jsonValid?: string;
}

/** Team configuration loaded from teams/*.json. */
export interface TeamConfig {
  name: string;
  displayName: string;
  description: string;
  members: string[];
  orchestrator?: string;
  mode?: 'round-robin' | 'orchestrated' | 'pipeline';
  maxRoundsPerMember?: number;
  discussionRounds?: number;
  voting?: boolean;
  maxAttempts?: number;
  acceptance?: AcceptanceCriteria;
  stations?: Record<string, { acceptance?: AcceptanceCriteria; maxAttempts?: number }>;
}

/** A single step in a plan generated by the Goal Orchestrator (/goal). */
export interface PlanStep {
  agentName: string;
  task: string;
}

/** Character configuration loaded from characters/*.json. */
export interface CharacterConfig {
  name: string;
  displayName: string;
  aiName?: string;
  role?: string;        // Single legacy role
  roles?: string[];     // Multi-Skill list of unlocked roles
  activeRole?: string;  // Currently equipped role/skill
  trait: string;
  description: string;
  signature?: string;   // Optional concise summary for orchestrator
  reasoningEffort?: string;
}

/** Request payload for executing a child subagent (T22.7). */
export interface SubagentRunRequest {
  /** Task description string or structured TaskPacket */
  task: string | unknown;
  roleName?: string;
  traitName?: string;
  charName?: string;
  reasoningEffort?: string;
  /** When true, child prompt requires AgentResult JSON and runner parses the output. */
  expectAgentResult?: boolean;
  /** Restricts the subagent tools to a maximum allowable perimeter (T22.8). */
  allowedTools?: string[];
  /** Explicit run ID override for blackboard / report scoping. */
  runId?: string;
  /** Whether to record execution to persistent memory outside blackboard. Defaults to true. */
  persistMemory?: boolean;
  /** If true, runner re-throws child execution errors instead of returning typed failure. */
  throwOnError?: boolean;
}

/** Execution callbacks and signal for subagent run. */
export interface SubagentExecutionContext {
  onChunk?: (chunk: string, channel?: any, authorName?: string) => void;
  onStats?: (stats: any, agentLabel?: string) => void;
  onEvent?: (event: any) => void;
  signal?: AbortSignal;
}

/** Typed outcome of a subagent run. */
export interface SubagentRunResult {
  success: boolean;
  output: string;
  agentLabel: string;
  roleName: string;
  reportPath: string;
  stats?: unknown;
  agentResult?: unknown;
  error?: Error;
}

/** Contract for subagent runners (T22.7). */
export interface ISubagentRunner {
  run(request: SubagentRunRequest, context?: SubagentExecutionContext): Promise<SubagentRunResult>;
}

/**
 * Normalized context pressure representation (T22.2).
 */
export interface ContextPressure {
  usedTokens: number;
  limitTokens: number;
  remainingTokens: number;
  ratio: number;
}
