/**
 * Shared types for multi-agent protocol and orchestration layer (T4.1).
 * Focuses on shared communication contracts: chat messages, tool calls,
 * turn outcomes, and team/plan configurations.
 */

export type ChatRole = 'system' | 'user' | 'assistant' | 'tool';

/** Tool call structure matching OpenAI-compatible Function Calling specifications. */
export interface ToolCall {
  id: string;
  type: 'function';
  function: { name: string; arguments: string };
}

/** Chat message structure used across Agent, ILLMProvider, and team/goal histories. */
export interface ChatMessage {
  role: ChatRole;
  content: string | null;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
  name?: string;
}

/** Outcome of an execution turn (team member, pipeline station, or goal step). */
export type TurnOutcome = 'completed' | 'interrupted' | 'continue' | 'failed';

/**
 * Origin of a protocol decision (T2.1):
 * structured tool call (report_status/route_next/cast_vote) -> textual regex fallback -> default.
 */
export type ProtocolSource = 'tool_call' | 'regex' | 'fallback';

/** Cast vote in a discussion round with voting enabled. */
export type Vote = 'APPROVO' | 'MODIFICARE' | 'RIFIUTO';

import type { AcceptanceCriteria } from './loop';

/** Team configuration loaded from teams/*.json. */
export interface TeamConfig {
  name: string;
  displayName: string;
  description: string;
  members: string[];
  orchestrator?: string;
  mode?: 'round-robin' | 'orchestrated' | 'pipeline';
  maxRoundsPerMember?: number;
  discussionRounds?: number;
  voting?: boolean;
  maxAttempts?: number;
  acceptance?: AcceptanceCriteria;
  stations?: Record<string, { acceptance?: AcceptanceCriteria; maxAttempts?: number }>;
}

/** A single step in a plan generated by the Goal Orchestrator (/goal). */
export interface PlanStep {
  agentName: string;
  task: string;
}

/** Character configuration loaded from characters/*.json. */
export interface CharacterConfig {
  name: string;
  displayName: string;
  aiName?: string;
  role?: string;        // Single legacy role
  roles?: string[];     // Multi-Skill list of unlocked roles
  activeRole?: string;  // Currently equipped role/skill
  trait: string;
  description: string;
  signature?: string;   // Optional concise summary for orchestrator
  reasoningEffort?: string;
}
